export const COPY = {
  en: {
    tHome: "Home", tServices: "Services", tWork: "Work", tContact: "Contact", tReel: "Reel", tClients: "Clients",
    tCta: "Let's talk", tCtaLong: "Let's talk about your place", tSeeWork: "See the work",
    tEyebrowHero: "ONE STOP SOLUTION TO ALL YOUR DIGITAL NEEDS",
    tHeroA: "ONE TEAM FOR", tHeroB: "EVERYTHING YOU", tHeroC: "PUT ONLINE.",
    tHeroSub: "We look after the social accounts, the website and the films for restaurants, hotels and luxury houses in Paris. It's all one team, so nothing gets lost between agencies and everything sounds like you.",
    tHeroReassure: "A real person replies, usually the same day.",
    tStatClients: "CLIENTS WE LOOK AFTER", tStatTeam: "TEAM, ONE PERSON YOU CALL", tStatFirst: "WE WORK IN BOTH, ALWAYS",
    tDragHint: "Drag the tower — the hour follows",
    tGameStart: "Tap the tower to light it back up", tGameOn: "Tap a section to light or dim it", tGameDone: "Fully lit — tap a section to dim it",
    tNight: "NIGHT", tDusk: "DUSK", tDawn: "DAWN",
    tThreeLanesA: "Three lanes.", tThreeLanesB: "One team.",
    tMore: "See the service",
    tSocial: "Social media management", tWeb: "Website development", tVideo: "AI video",
    tSocialPitch: "We take the whole account off your desk — what gets shot, what gets posted, what gets promoted, and who answers the messages. You see the plan, we handle the rest.",
    tWebPitch: "Most people meet you on their phone before they ever walk in. We build the site that makes them want to, and makes reserving take seconds.",
    tVideoPitch: "Proper films, without shutting your dining room for two days. We build them with AI and finish them by hand, so you get the images without losing a service.",
    tRecentWorkA: "Recent work,", tRecentWorkB: "and how it's doing.", tAllWork: "All work",
    tHoverPause: "Hover to pause the strip.",
    tProcess: "Process", tProcessTitleA: "How a project", tProcessTitleB: "actually runs.",
    tWeek: "Week", tOngoing: "Ongoing",
    tStep1: "Audit & plan", tStep2: "Direction", tStep3: "Production & launch", tStep4: "Review & repeat",
    tStep1Body: "We come and see the place, look at who's already coming, and read what you've published so far. Then we write down what we'd change first, and why.",
    tStep2Body: "You see the look, the voice and the first set of work before we go wide. If something isn't you, this is the cheap moment to say so.",
    tStep3Body: "We shoot, we build, we publish. The posts start going out, the site goes live, and the campaigns begin bringing people through the door.",
    tStep4Body: "We sit down regularly to look at what worked, drop what didn't, and decide what's next. No jargon, nothing you can't repeat to an owner.",
    tFaq: "FAQ", tFaqTitle: "Questions we get asked.",
    tQ1: "Can we take just one service?", tQ2: "Who do you usually work with?",
    tQ3: "How are engagements structured?", tQ4: "Do you need our own footage?", tQ5: "How do we start?",
    tA1: "Of course. Most people start with the thing that's bothering them most and add the rest later, once they know how we work.",
    tA2: "Restaurants, hotels and luxury houses — places where the room is held to a high standard and the online side should be too.",
    tA3: "We agree what we're doing and what it costs before anything starts, and you have one person to call throughout.",
    tA4: "Not always. We can shoot at your place, use what you already have, or create the shots that don't exist yet. Often all three.",
    tA5: "Send us a few lines about your place. We'll read it properly and come back to you, usually the same day.",
    tFinalA: "Let's talk about", tFinalB: "your place.",
    tFinalSub: "Tell us what's frustrating you — an empty Tuesday, a site nobody books through, photos that don't look like the room. If we're not the right people for it, we'll say so early.",
    tServicesHeroA: "Everything digital,", tServicesHeroB: "under one roof.",
    tServicesSub: "Three services that hold each other up: the content gives the site something to say, the site turns attention into reservations, and the films make both look like the place they represent.",
    tSocialLong: "We run the account like it's our own room to fill: what goes out, when, and what it's meant to do. You get one person to talk to and a report you can actually read.",
    tSocial1: "Strategy & content calendar", tSocial2: "Art direction & tone of voice", tSocial3: "Photo & reel production",
    tSocial4: "Paid campaigns & targeting", tSocial5: "Community & replies", tSocial6: "Influencer & press coordination",
    tSocial7: "Personal branding for founders", tSocial8: "Monthly performance review",
    tWebLong: "Everything on the page is there to get someone to one action: book a table, take a room, ask about a private evening. We design and build it ourselves, and leave your team able to keep it up to date.",
    tWeb1: "Design & UX", tWeb2: "Development & hosting", tWeb3: "Booking & reservation flows",
    tWeb4: "Campaign landing pages", tWeb5: "Bilingual FR / EN", tWeb6: "SEO & local search",
    tWeb7: "Speed & accessibility", tWeb8: "Analytics & tracking",
    tAnatomy: "ANATOMY OF A PAGE THAT CONVERTS",
    tReserveBtn: "RESERVE", tAnnoCta: "one action, always visible",
    tAnnoHero: "HERO FILM OR STILL", tAnnoRooms: "rooms, menus, private events",
    tAnnoCal: "live availability", 
    tVideoLong: "We build the films with generative tools and finish them the old-fashioned way — colour, sound, typography, taste. Nobody blocks your entrance with a truck, and you don't lose a service to a shoot.",
    tVid1: "Campaign films", tVid2: "Brand & house films", tVid3: "Vertical sets for social",
    tVid4: "Product & menu films", tVid5: "Titles & motion graphics", tVid6: "Grade, sound & finish",
    tVid7: "Every ratio delivered", tVid8: "Overnight revisions",
    tWorkHeroA: "Selected work,", tWorkHeroB: "grouped by service.",
    tContactHeroA: "Tell us about", tContactHeroB: "your place.",
    tContactSub: "A few lines is plenty — what you run, what's not working, and when you'd like it sorted. We read everything ourselves.",
    tFirstReply: "We reply", tSameDay: "Usually the same day", tLanguages: "We work in", tBasedIn: "We're in",
    tBriefForm: "TELL US A BIT", tName: "Your name", tBusiness: "Your place", tServiceNeeded: "What you're after",
    tMessage: "What's on your mind?", tSendWhatsapp: "Send it over",
    tFormNote: "No forms, no funnels — it comes straight to us and we answer ourselves.",
    tTagline: "One stop solution to all your digital needs.", tStudio: "Studio",
    tSeeAll: "See all", tEmail: "bonjour@telabs.fr", tPhone: "+33 1 00 00 00 00",
    tFaqHint: "Tap a question", tTalk: "Prefer to talk it through?", tTalkCta: "Send us a note",
    tJump: "Jump to"
  },
  fr: {
    tHome: "Accueil", tServices: "Services", tWork: "Réalisations", tContact: "Contact", tReel: "Réel", tClients: "Clients",
    tCta: "Parlons-en", tCtaLong: "Parlons de votre établissement", tSeeWork: "Voir les réalisations",
    tEyebrowHero: "UNE SEULE ÉQUIPE POUR TOUS VOS BESOINS DIGITAUX",
    tHeroA: "UNE ÉQUIPE POUR", tHeroB: "TOUT CE QUE VOUS", tHeroC: "PUBLIEZ EN LIGNE.",
    tHeroSub: "Nous nous occupons des réseaux sociaux, du site et des films des restaurants, hôtels et maisons de luxe parisiens. Une seule équipe : rien ne se perd entre deux agences, et tout vous ressemble.",
    tHeroReassure: "Une vraie personne vous répond, souvent le jour même.",
    tStatClients: "CLIENTS ACCOMPAGNÉS", tStatTeam: "ÉQUIPE, UNE PERSONNE À APPELER", tStatFirst: "NOUS TRAVAILLONS DANS LES DEUX",
    tDragHint: "Faites tourner la tour — l'heure suit",
    tGameStart: "Touchez la tour pour la rallumer", tGameOn: "Touchez une section pour l'allumer ou l'éteindre", tGameDone: "Tout est illuminé — touchez pour éteindre",
    tNight: "NUIT", tDusk: "CRÉPUSCULE", tDawn: "AUBE",
    tThreeLanesA: "Trois métiers.", tThreeLanesB: "Une équipe.",
    tMore: "Voir le service",
    tSocial: "Gestion des réseaux sociaux", tWeb: "Création de sites web", tVideo: "Vidéo IA",
    tSocialPitch: "Nous prenons tout le compte en main : ce qu'on tourne, ce qu'on publie, ce qu'on sponsorise, et qui répond aux messages. Vous voyez le plan, nous faisons le reste.",
    tWebPitch: "On vous découvre sur un téléphone avant de franchir la porte. Nous faisons le site qui donne envie de venir, et où réserver prend quelques secondes.",
    tVideoPitch: "De vrais films, sans fermer la salle deux jours. Nous les créons avec l'IA et les finissons à la main : vous avez les images sans perdre un service.",
    tRecentWorkA: "Travaux récents,", tRecentWorkB: "et ce qu'ils donnent.", tAllWork: "Tout voir",
    tHoverPause: "Survolez pour mettre en pause.",
    tProcess: "Méthode", tProcessTitleA: "Comment se déroule", tProcessTitleB: "un projet.",
    tWeek: "Semaine", tOngoing: "En continu",
    tStep1: "Audit & plan", tStep2: "Direction", tStep3: "Production & lancement", tStep4: "Bilan & suite",
    tStep1Body: "Nous venons voir le lieu, regardons qui vient déjà et lisons ce que vous avez publié. Puis nous écrivons ce que nous changerions en premier, et pourquoi.",
    tStep2Body: "Vous voyez le style, le ton et les premiers contenus avant tout déploiement. Si ce n'est pas vous, c'est le bon moment pour le dire.",
    tStep3Body: "Nous tournons, nous développons, nous publions. Les publications sortent, le site est en ligne, les campagnes font venir du monde.",
    tStep4Body: "Nous faisons le point régulièrement : ce qui marche, ce qu'on arrête, ce qu'on fait ensuite. Sans jargon, transmissible à un propriétaire.",
    tFaq: "FAQ", tFaqTitle: "Les questions fréquentes.",
    tQ1: "Peut-on prendre un seul service ?", tQ2: "Avec qui travaillez-vous ?",
    tQ3: "Comment se structurent les missions ?", tQ4: "Faut-il nos propres images ?", tQ5: "Comment commencer ?",
    tA1: "Bien sûr. La plupart commencent par ce qui les gêne le plus et ajoutent le reste ensuite, une fois qu'ils savent comment nous travaillons.",
    tA2: "Restaurants, hôtels et maisons de luxe — des lieux tenus à un haut niveau d'exigence, qui mérite d'exister aussi en ligne.",
    tA3: "Nous convenons du périmètre et du budget avant de commencer, et vous avez une seule personne à appeler tout du long.",
    tA4: "Pas toujours. Nous pouvons tourner chez vous, utiliser vos images existantes, ou créer les plans qui n'existent pas encore.",
    tA5: "Écrivez-nous quelques lignes sur votre établissement. Nous les lisons vraiment et revenons vers vous, souvent le jour même.",
    tFinalA: "Parlons de", tFinalB: "votre établissement.",
    tFinalSub: "Dites-nous ce qui vous agace : un mardi vide, un site qui ne génère aucune réservation, des photos qui ne ressemblent pas à la salle. Si nous ne sommes pas les bonnes personnes, nous le dirons tout de suite.",
    tServicesHeroA: "Tout le digital,", tServicesHeroB: "sous un même toit.",
    tServicesSub: "Trois services qui se soutiennent : le contenu donne au site quelque chose à dire, le site transforme l'attention en réservations, et les films donnent aux deux l'image du lieu.",
    tSocialLong: "Nous gérons le compte comme si la salle était la nôtre : ce qui sort, quand, et dans quel but. Une seule personne à qui parler, et un rapport vraiment lisible.",
    tSocial1: "Stratégie & calendrier éditorial", tSocial2: "Direction artistique & ton", tSocial3: "Production photo & reels",
    tSocial4: "Campagnes payantes & ciblage", tSocial5: "Communauté & réponses", tSocial6: "Influence & relations presse",
    tSocial7: "Personal branding des fondateurs", tSocial8: "Bilan de performance mensuel",
    tWebLong: "Tout sur la page sert une seule action : réserver une table, une chambre, demander une soirée privée. Nous concevons et développons nous-mêmes, et votre équipe peut ensuite le faire vivre.",
    tWeb1: "Design & UX", tWeb2: "Développement & hébergement", tWeb3: "Parcours de réservation",
    tWeb4: "Landing pages de campagne", tWeb5: "Bilingue FR / EN", tWeb6: "SEO & recherche locale",
    tWeb7: "Performance & accessibilité", tWeb8: "Analytics & suivi",
    tAnatomy: "ANATOMIE D'UNE PAGE QUI CONVERTIT",
    tReserveBtn: "RÉSERVER", tAnnoCta: "une action, toujours visible",
    tAnnoHero: "FILM OU IMAGE D'ACCUEIL", tAnnoRooms: "chambres, cartes, événements privés",
    tAnnoCal: "disponibilités en direct",
    tVideoLong: "Nous créons les films avec des outils génératifs et les finissons à l'ancienne : étalonnage, son, typographie, goût. Personne ne bloque votre entrée avec un camion, et vous ne perdez aucun service.",
    tVid1: "Films de campagne", tVid2: "Films de marque", tVid3: "Formats verticaux",
    tVid4: "Films produit & carte", tVid5: "Générique & motion design", tVid6: "Étalonnage, son & finition",
    tVid7: "Tous les formats livrés", tVid8: "Retouches du jour au lendemain",
    tWorkHeroA: "Réalisations,", tWorkHeroB: "par service.",
    tContactHeroA: "Parlez-nous de", tContactHeroB: "votre établissement.",
    tContactSub: "Quelques lignes suffisent : ce que vous tenez, ce qui ne va pas, et pour quand. Nous lisons tout nous-mêmes.",
    tFirstReply: "Nous répondons", tSameDay: "Souvent le jour même", tLanguages: "Nous travaillons en", tBasedIn: "Nous sommes à",
    tBriefForm: "DITES-NOUS UN MOT", tName: "Votre nom", tBusiness: "Votre établissement", tServiceNeeded: "Ce que vous cherchez",
    tMessage: "Qu'avez-vous en tête ?", tSendWhatsapp: "Envoyer",
    tFormNote: "Pas de formulaire perdu : le message nous arrive et nous répondons nous-mêmes.",
    tTagline: "Une seule équipe pour tous vos besoins digitaux.", tStudio: "Studio",
    tSeeAll: "Tout voir", tEmail: "bonjour@telabs.fr", tPhone: "+33 1 00 00 00 00",
    tFaqHint: "Cliquez sur une question", tTalk: "Vous préférez en parler ?", tTalkCta: "Écrivez-nous",
    tJump: "Aller à"
  }
};
